spring.datasource.url=jdbc:mysql://localhost:3306/booking_bot?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#logging.level.liquibase=DEBUG
#logging.level.liquibase.changelog=DEBUG

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.servlet.context-path=/api
# не забудь включити або видалити коли будеш працювати з докером
spring.docker.compose.enabled=false
bot.token=8215840726:AAH-mgDv1z1IrPnCxsRZu52v7qogF-tpE4M

